app/routes/auth_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from werkzeug.security import generate_password_hash, check_password_hash
from app.modules import *
from app.data.data_base import *
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user


auth_bp = Blueprint('auth', __name__)
login_manager = LoginManager()
login_manager.init_app(auth_bp)


@auth_bp.route('/login', methods=["POST", "GET"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('home.home'))

    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        rem = request.form.get('remember', 'off')
        user = get_users_by_email(email)

        if not user:
            flash("Email doesn't exist", "danger")
            return redirect(url_for('auth.login'))

        user = user[0]

        if check_password_hash(user['password'], password):
            user_obj = User(
                id=user["id"],
                name=user["name"],
                email=user["email"],
                password=user["password"],
                DOB=user["birthday"],
                gender=user["sex"],
                rem=rem
            )
            login_user(user_obj, remember=user_obj.remember())
            return redirect(url_for('home.home'))
        else:
            flash('Invalid email or password', 'danger')
            return redirect(url_for('auth.login'))

    return render_template('login.html')


@auth_bp.route('/register', methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('home.home'))

    if request.method == 'POST':

        email = request.form.get('email')
        name = request.form.get('username')
        password = request.form.get('password')
        confirm_password = request.form.get('confirm_password')
        DOB = request.form.get('dob')
        gender = request.form.get('gender')
        users_list = get_users()

        valid = validate_email_format(email)

        for user in users_list:
            if user['name'] == name:
                flash('Username is already registered', 'danger')
                return render_template('register.html')

            if user['email'] == email:
                flash('Email is already registered', 'danger')
                return render_template('register.html')

        if not validate_email_format(email):
            flash("Invalid email format", "danger")
            return render_template('register.html')

        if len(password) < 8:
            flash('Your password must have more than 8 characters', 'danger')
            return render_template('register.html')

        if not any(char.isalpha() for char in password):
            flash('Your password must contain at least one letter', 'danger')
            return render_template('register.html')

        if not any(char.isupper() for char in password):
            flash('Your password must contain at least one uppercase letter', 'danger')
            return render_template('register.html')

        if not any(char.islower() for char in password):
            flash('Your password must contain at least one lowercase letter', 'danger')
            return render_template('register.html')

        if not any(char.isdigit() for char in password):
            flash('Your password must contain at least one digit ', 'danger')
            return render_template('register.html')

        if any(char.isspace() for char in password):
            flash("Your password can't contain spaces", 'danger')
            return render_template('register.html')

        special_characters = '!@#$%^&*(),.?":{}|<>'
        special_characters_list = list(special_characters)
        if not any(special_characters_list for special_character in password):
            flash('Your password must contain at least one special character', 'danger')
            return render_template('register.html')

        if password != confirm_password:
            flash("Passwords don't match", 'danger')
            return render_template('register.html')

        hash_password = generate_password_hash(password)
        add_user_to_users(name, email, hash_password, DOB, gender)

        flash('Registration successful! You can now log in', 'success')
        return redirect(url_for('auth.login'))

    return render_template('register.html')


@auth_bp.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    if request.method == 'POST':
        logout_user()
        flash('You have been logged out.', 'info')
        return redirect(url_for('auth.login'))
    return render_template('logout.html')

app/routes/post_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user
from app.data.data_base import *
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user
from app.modules import *

post_bp = Blueprint('post', __name__)
login_manager = LoginManager()
login_manager.init_app(post_bp)


@post_bp.route('/post/<int:id>', methods=['POST', 'GET'])
@login_required
def post(id):
    user_id = current_user.id
    post_data = get_post_by_id(id)
    if not post_data:
        return redirect(url_for('explore'))

    post_author_id = get_user_id_by_post_id(id)
    post_author = get_user_by_id(post_author_id)

    comment_author_id = get_all_author_id_by_comment()
    comment_author = get_users_by_list_id(comment_author_id)

    title = post_data[0]['title']
    content = post_data[0]['content']
    image_url = post_data[0].get('image_url')
    video_url = post_data[0].get('video_url')
    video_url = get_embed_url(video_url)
    comments = get_all_comments_by_post_id(id)
    user_id = current_user.id
    is_post_author = user_id == post_author_id

    for comment in comments:
        comment_author = get_user_by_id(comment['user_id'])
        comment['author_name'] = comment_author['name']
        comment['author_id'] = comment_author['id']

    if request.method == 'POST':
        comment = request.form.get('comment')
        if comment:
            add_comment(user_id, id, comment)
            flash('Your comment has been added!', 'success')
            return redirect(url_for('post.post', id=id))

    return render_template('post.html',
                           title=title, content=content, id=id, comments=comments,
                           post_author=post_author['name'], post_author_id=post_author_id,
                           image_url=image_url, video_url=video_url, user_id=user_id,
                           is_post_author=is_post_author, comment_author=comment_author)


@post_bp.route('/addpost', methods=["GET", "POST"])  # Corrected the decorator
@login_required
def addpost():
    user_id = current_user.id
    all_user_posts = get_all_posts_by_user_id(user_id)
    for post in all_user_posts:
        if post.get('video_url'):
            post['video_url'] = get_embed_url(post['video_url'])
    if request.method == 'POST':
        title = request.form.get('title')
        content = request.form.get('content')
        post_img = request.files.get('post_img')
        post_video = request.form.get('post_video')

        if not title or not content:
            flash('Please fill out all required fields.', 'danger')
            return render_template('addpost.html')

        image_url = None

        if post_img:
            image = post_img.filename
            image_path = f'app/static/downloaded_images/{image}'
            post_img.save(image_path)
            image_url = url_for('static', filename=f'downloaded_images/{image}')

        create_new_post(user_id, title, content, image_url, post_video)
        flash('Post created successfully!', 'success')
        return redirect(url_for('profile.profile'))

    return render_template('addpost.html', all_post=all_user_posts)


@post_bp.route('/delete_post', methods=['GET', 'POST'])  # Corrected the decorator
@login_required
def delete_post():
    user_id = current_user.id
    all_user_posts = get_all_posts_by_user_id(user_id)
    for post in all_user_posts:
        if post.get('video_url'):
            post['video_url'] = get_embed_url(post['video_url'])

    if request.method == 'POST':
        post_title = request.form.get('delete_post')
        if post_title:
            post = get_post_by_title_and_user_id(post_title, user_id)
            if post:
                delete_post_by_id(post['id'])
                flash("Post deleted successfully", 'success')
                return redirect(url_for('post.delete_post'))
            else:
                flash("No post found with that title.", 'danger')
                return redirect(url_for('post.delete_post'))

    return render_template('delete_post.html', user_id=user_id, all_post=all_user_posts)


@post_bp.route('/explore', methods=['POST', 'GET'])  # Corrected the decorator
@login_required
def explore():
    all_posts = get_all_posts()

    for post in all_posts:
        if post.get('video_url'):
            post['video_url'] = get_embed_url(post['video_url'])

    if request.method == 'POST':
        title = request.form.get('explore_input').strip()
        posts_by_title = get_post_by_title_partial(title)

        for post in posts_by_title:
            if post.get('video_url'):
                post['video_url'] = get_embed_url(post['video_url'])

        if posts_by_title:
            return render_template('explore.html', all_post=posts_by_title, search=title)
        else:
            flash('No posts found for the search query.', 'danger')
            return render_template('explore.html', all_post=None, search=title)

    return render_template('explore.html', all_post=all_posts)


@post_bp.route('/delete_comment/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_comment(id):
    comment = get_comment_by_id(id)

    if not comment:
        flash("Comment not found.", "danger")
        return redirect(url_for("home.home"))

    post_id = comment[0]['post_id']
    post = get_post_by_id(post_id)

    if not post:
        flash("Post not found.", "danger")
        return redirect(url_for("home.home"))

    comment_owner = comment[0]['user_id']
    user_id = current_user.id

    if comment_owner != user_id:
        flash("You are not the owner of this comment to delete it.", "danger")
        return redirect(url_for("post.post", id=post_id))

    if request.method == 'POST':
        delete_comment_by_id(id)
        flash("Comment deleted successfully.", "success")
        return redirect(url_for("post.post", id=post_id))

    return render_template('delete_comment.html', comment=comment[0], post_id=post_id)

app/templates/addpost.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add post</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
        <header class="header">
            <div class="container">
                <nav class="header__nav">
                    <div class="header__div">
                    <ul class="header__list__nav">
                        <li class="header__item__nav">
                            <a href="/">Home</a>
                        </li>
                        <li class="header__item__nav">
                            <a href="/explore">Explore</a>
                        </li>
                        <li class="header__item__nav">
                            <a href="/addpost">Add a post</a>
                        </li>
                        <li class="header__item__nav">
                            <a href="/delete_post">Delete a post</a>
                        </li>
                        <li class="header__item__nav">
                            <a href="/all_users">All users</a>
                        </li>
                    </ul>
                    </div>
                </nav>
            </div>
        </header>
                    {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <div class="flash-messages">
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endwith %}
    <main class="register">
        <div class="container">
            <form class="form__register" action="{{ url_for('post.addpost') }}" method="POST" enctype="multipart/form-data">
                <h1 class="register__main__title">X-Whisper</h1>
                <h1 class="explore__h1">New post</h1>
                <br>
                <ul class="form__register__list">
                    <li class="form__register__item">
                        <label class="form__register__item__label" for="title">Post title:</label>
                        <h6>*required</h6>
                        <input class="form__register__item__input" type="text" id="title" name="title" required>
                    </li>
                    <li class="form__register__item">
                        <label class="form__register__item__label" for="content">Post content:</label>
                        <h6>*required</h6>
                        <input class="form__register__item__input" type="text" id="content" name="content" required>
                    </li>
                    <li class="form__register__item">
                        <label class="form__register__item__label" for="post_img">Image (optional):</label>
                        <input class="form__register__item__input" type="file" id="post_img" name="post_img" accept="image/*">
                    </li>
                    <li class="form__register__item">
                        <label class="form__register__item__label" for="post_video">Video/gif (url) (optional):</label>
                        <input class="form__register__item__input" type="text" id="post_video" name="post_video">
                    </li>
                </ul>
                <input class="form__register__btn" type="submit" value="Add post">
            </form>
        </div>
    </main>
    <h1 class="add__post_h1">Your posts</h1>
    <main>
        <div class="container">
            <section class="section__post">
                <ul class="section__post__list">
                    {% for post in all_post|sort(attribute='id', reverse=True) %}
                        <li class="section__post__item">
                            <a href="/post/{{post['id']}}">
                                <h3 class="section__post__item__title">{{ post['title'] }}</h3>
                                <p class="section__post__item__text">{{ post['content']}}</p>
                                <img class="section__post__item__img" src="{{ post['image_url'] }}" alt="">
                            </a>
                            {% if post['video_url'] %}
                            <iframe class="section__post__item__media__video"
                                    src="{{ post['video_url'] }}"
                                    frameborder="0"
                                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                    allowfullscreen></iframe>
                        {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            </section>
        </div>
    </main>
</body>
</html>

app/templates/explore.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Explore</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
    <header class="header">
        <div class="container">
            <nav class="header__nav">
                <div class="header__div">
                    <ul class="header__list__nav">
                        <li class="header__item__nav">
                            <a href="/">Home</a>
                        </li>
                        <li class="header__item__nav">
                            <a href="/explore">Explore</a>
                        </li>
                        <li class="header__item__nav">
                            <a href="/addpost">Add a post</a>
                        </li>
                        <li class="header__item__nav">
                            <a href="/delete_post">Delete a post</a>
                        </li>
                        <li class="header__item__nav">
                            <a href="/all_users">All users</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <h1 class="register__main__title">X-Whisper</h1>
    <h1 class="explore__h1">Explore</h1>
    <br><br><br>
    <main>
        <div>
            <form class="form__register" action="{{ url_for('post.explore') }}" method="POST">
                <ul class="form__register__list">
                    <li class="form__register__item">
                        <label class="form__register__item__label" for="explore_input">Enter The Post Title To Find A Post:</label>
                        <input class="form__register__item__input" type="text" id="explore_input" name="explore_input" value="{{ search if search else '' }}" required>
                        <input class="explore__input" type="submit" value="Search">
                    </li>
                </ul>
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                <div class="flash-messages">
                    {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
                {% endwith %}
            </form>
        </div>
        <section class="section__post">
            <br><br>
            <h1 class="add__post_h1">{{ 'Search Results for: ' + search if search else 'All Posts' }}</h1>
            <br><br><br>
            <div class="container">
                {% if not all_post %}
                <div class="no-posts">
                    <h2>No posts found.</h2>
                </div>
                {% else %}
                <ul class="section__post__list">
                    {% for post in all_post|sort(attribute='id', reverse=True) %}
                    <li class="section__post__item">
                        <a href="/post/{{post['id']}}">
                            <h2 class="section__post__item__title">{{ post['title'] }}</h2>
                            <h3 class="section__post__item__text">{{ post['content'] }}</h3>
                            {% if post['image_url'] %}
                            <img class="section__post__item__img" src="{{ post['image_url'] }}" alt="Post Image">
                            {% endif %}
                        </a>
                        {% if post['video_url'] %}
                        <div class="section__post__item__media">
                            <iframe class="section__post__item__media__video" src="{{ post['video_url'] | replace('watch?v=', 'embed/') }}" frameborder="0"></iframe>
                        </div>
                        {% endif %}
                    </li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
        </section>
    </main>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>

<body>
    <main class="login">
        <div class="container">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <div class="flash-messages">
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endwith %}
            <form class="form__login" action="/login" method="POST">
                <h1 class="login__main__title">X-Whisper</h1>
                <p class="form__login__text">You need to be logged in to join our forum</p>
                <h2 class="login__title">Log in</h2>
                <ul class="form__login__list">
                    <li class="form__login__item">
                        <label class="form__login__item__label" for="email">Email:</label>
                        <input class="form__login__item__input" type="email" id="email" name="email" required>
                    </li>
                    <li class="form__login__item">
                        <label class="form__login__item__label" for="password">Password:</label>
                        <input class="form__login__item__input" type="password" id="password" name="password" required>
                    </li>
                    <li class="form__login__item">
                        <div class="form__login__item__check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1" name="remember">
                            <label class="form-check-label" for="exampleCheck1">Remember me</label>
                        </div>
                    </li>
                </ul>
                <input class="form__login__btn" type="submit" value="Log in">
                <li class="dont_have">
                    <h2 class="form__login__item__text">Don't have an account?
                        <a href="{{ url_for('auth.register') }}" class="form__login__item__link">Register now</a>
                    </h2>
                </li>
            </form>
        </div>
    </main>
</body>

</html>

app/templates/post.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>

<body>
<header class="header">
    <div class="container">
        <nav class="header__nav">
            <div class="header__div">
                <ul class="header__list__nav">
                    <li class="header__item__nav">
                        <a href="/">Home</a>
                    </li>
                    <li class="header__item__nav">
                        <a href="/explore">Explore</a>
                    </li>
                    <li class="header__item__nav">
                        <a href="/addpost">Add a post</a>
                    </li>
                    <li class="header__item__nav">
                        <a href="/delete_post">Delete a post</a>
                    </li>
                    <li class="header__item__nav">
                        <a href="/all_users">All users</a>
                    </li>
                </ul>
            </div>
        </nav>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div class="flash-messages">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}
        {% endwith %}
    </div>
</header>
<main>
    <section class="section__post">
        <div class="container">
            <ul class="section__post__list">
                <li class="section__post__item">
                    <h2><a class="register__btn" href="{{ url_for('profile.view_profile', id=post_author_id) }}">{{
                        post_author
                        }}</a></h2>
                    <br><br>
                    <h1 class="section__post__item__title">{{ title }}</h1>
                    <br>
                    <h3>{{ content }}</h3>
                    {% if image_url %}
                    <img class="section__post__item__img" src="{{ image_url }}" alt="Post image">
                    {% endif %}
                    {% if video_url %}
                    <iframe class="section__post__item__media__video"
                            src="{{ video_url }}"
                            frameborder="0"
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                            allowfullscreen></iframe>
                    {% endif %}
                    {% if is_post_author %}
                    <a class="delete__post" href="{{ url_for('post.delete_post', id=id) }}">DELETE POST</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </section>
    <section class="section__post">
        <div class="container">
            <form class="form__comment" method="POST">
                <input type="hidden" name="post_id" value="{{ id }}">
                <label class="comment__label" for="comment">Your Comment:</label>
                <textarea class="comment__input" id="comment" name="comment" rows="6" required></textarea>
                <button class="submit__button form__comment__button" type="submit">Submit Comment</button>
            </form>
            <h3 class="comment__title">Comments:</h3>
            <ul class="section__post__list">
                {% for comment in comments|sort(attribute='id', reverse=True) %}
                <li class="section__post__item">
                    <h4><a class="register__btn" href="{{ url_for('profile.view_profile', id=comment['author_id']) }}">{{
                        comment['author_name'] }} </a></h4>
                    <h3 class="section__post__item__title">{{ comment['comment'] }}</h3>
                    {% if comment['user_id'] == user_id %}
                    <form action="{{ url_for('post.delete_comment', id=comment['id']) }}" method="POST"
                          style="display:inline;">
                        <button type="submit" class="delete__post">DELETE COMMENT</button>
                    </form>
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
        </div>
    </section>
</main>

</body>

</html>

app/templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
</head>

<body>
    <main class="register">
        <div class="container">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <div class="flash-messages">
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endwith %}
            <form class="form__register" action="{{ url_for('auth.register') }}" method="POST">
                <h1 class="register__main__title">X-Whisper</h1>
                <h3 class="register__title">Register</h3>
                <ul class="form__register__list">
                    <li class="form__register__item">
                        <label class="form__register__item__label" for="username">Username:</label>
                        <input class="form__register__item__input" type="text" id="username" name="username" required>
                    </li>
                    <li class="form__register__item">
                        <label class="form__register__item__label" for="email">Email:</label>
                        <input class="form__register__item__input" type="email" id="email" name="email" required>
                    </li>
                    <li class="form__register__item">
                        <label class="form__register__item__label" for="password">Password:</label>
                        <input class="form__register__item__input" type="password" id="password" name="password" required>
                    </li>
                    <li class="form__register__item">
                        <label class="form__register__item__label" for="confirm_password">Repeat password:</label>
                        <input class="form__register__item__input" type="password" id="confirm_password" name="confirm_password" required>
                    </li>
                    <li class="form__register__item">
                        <label class="form__register__item__label" for="dob">Date of birth:</label>
                        <input class="form__register__item__input" type="date" id="dob" name="dob" required>
                    </li>
                    <li class="form__register__item">
                        <label class="form__register__item__label" for="gender">Gender:</label>
                        <select class="form__register__item__input" id="gender" name="gender" required>
                            <option value="other">Other</option>
                            <option value="male">Male</option>
                            <option value="female">Female</option>
                        </select>
                    </li>
                </ul>
                <input class="form__register__btn" type="submit" value="Register">
            </form>
            <div class="register__link">
                <br>
                <h2>Already have an account?
                    <a href="{{ url_for('auth.login') }}" class="register__btn">Log in</a>
                </h2>
            </div>
        </div>
    </main>
</body>

</html>